<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Premier</name>
   <tag></tag>
   <elementGuidId>f3f0bd0d-da94-4f9b-96f1-7f094d04ae97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div/section[3]/div[2]/main[2]/div[1]/div/div[2]/div[2]/div/div[1]/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div/section[3]/div[2]/main[2]/div[1]/div/div[2]/div[2]/div/div[1]/div[3]/a</value>
   </webElementProperties>
</WebElementEntity>
